data:
  filename: res/KNOW_2017.pkl
  num_folds: 5
  fold_index: 0

model:
  embedding_size: 64
  hidden_size: 512
  intermediate_size: 1024
  num_hidden_layers: 18
  num_transform_blocks: 1
  num_attention_blocks: 1
  hidden_dropout_prob: 0.5
  attention_dropout_prob: 0.5
  drop_path_prob: 0.5
  embed_init_std: 0.02

optim:
  lr: 0.0003
  weight_decay: 0.01

train:
  epochs: 100
  batch_size: 128
  accumulate_grads: 1
  max_grad_norm: 1.0
  validation_interval: 1.0
  random_seed: 42
  precision: 32
